const serviceTypes = [
  "Food Waste",
  "Market Waste",
  "Fallen Stocks(Non Infectious)",
  "Animal Manure",
  "Slaughter House Waste",
  "Agricultural Farms",
  "Seaweed Waste",
  "Expired Food",
  "Household Organic Waste",
  "Domestic Sewage Sludge",
  "Inert / Street Sweeping",
  "Islamic Culture Reject",
  "Confiscated Goods",
  "Uncontaminated Soil",
  "Paper",
  "Tyres",
  "Wood",
  "Plastic",
  "Cardboard / Carton",
  "Textile / Fabric",
  "Rubber",
  "Broken Furniture",
  "Glass / Float Glass",
  "Non-Ferrous Metal Scrap",
  "Ferrous Metal Scrap",
  "End of Life Vehicle",
  "Concrete Waste",
  "Excavated Material",
  "Concrete Block",
  "Ceramics",
  "Gypsum Boards / Plasterboards",
  "Asphalt Paving",
  "Styrofoam",
  "Cutting Oil",
  "Transformer Oil",
  "Engine Oil",
  "Hydraulic Oil",
  "Pharmaceutical Waste",
  "Infectious",
  "Veterinary Waste",
  "Asbestos Containing Materials",
  "Asbestos",
  "Chemical Waste",
  "Containers with Hazardous",
  "Compressed Aerosol",
  "Used Oil Rags / Filters",
  "Explosives",
  "Waste Electrical and Electronic Equipment",
  "Batteries",
  "Collecting Of waste ships oil",
  "Kitchen Grease",
  "Cooking Oil",
  "Oily Sludge",
  "Sludge generated from Industrial Process",
  "Sludge from Industrial Waste / Water Treatment Plants",
  "Contaminated Domestic Waste" 
];

export default serviceTypes;
